version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solicitudesBD
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  usuario-ms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solicitudes-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/solicitudesBD
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
